# Generated by Django 5.2.3 on 2025-08-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpu",
            name="gpu_model",
        ),
    ]
