# Generated by Django 5.2.3 on 2025-08-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_gpu_gpu_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpu",
            name="gpu_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
