# Generated by Django 5.2.3 on 2025-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_gpu_gpu_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="NPR", max_length=3),
        ),
    ]
