# Generated by Django 5.2.3 on 2025-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_wallet_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="connection_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("CONNECTING", "Connecting"),
                    ("CONNECTED", "Connected"),
                    ("DISCONNECTED", "Disconnected"),
                    ("ERROR", "Error"),
                ],
                default="CONNECTING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="gpu_utilization",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="is_auto_reconnect",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="session",
            name="last_connected",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="memory_utilization",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="ssh_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="ssh_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="ssh_port",
            field=models.PositiveIntegerField(blank=True, default=22, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="ssh_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="temperature",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
