# Generated by Django 5.2.3 on 2025-08-26 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_session_connection_error_session_connection_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="host_email",
        ),
        migrations.RemoveField(
            model_name="host",
            name="host_name",
        ),
        migrations.RemoveField(
            model_name="host",
            name="host_password",
        ),
        migrations.RemoveField(
            model_name="renter",
            name="renter_email",
        ),
        migrations.RemoveField(
            model_name="renter",
            name="renter_name",
        ),
        migrations.RemoveField(
            model_name="renter",
            name="renter_password",
        ),
        migrations.AddField(
            model_name="host",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="renter",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renter_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
