# Generated by Django 5.2.3 on 2025-08-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_host_host_email_remove_host_host_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renter_profile', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to='auth.user'),
        ),
    ]
