# Generated by Django 5.2.3 on 2025-08-26 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_make_user_non_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayPort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("port", models.PositiveIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("LEASED", "Leased"),
                            ("RESERVED", "Reserved"),
                        ],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                ("leased_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leased_to_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relay_port",
                        to="api.session",
                    ),
                ),
            ],
        ),
    ]
