# Generated by Django 5.2.3 on 2025-08-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_relayport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
